version: green
replicaCount: 2

image:
  repository: hareesh88666/maven-web-application
  tag: "2"

service:
  type: ClusterIP
  port: 80

activeVersion: green     # TRAFFIC STILL GOES TO GREEN INITIALLY

ingress:
  enabled: false
  className: "nginx"

