version: blue
replicaCount: 2

image:
  repository: hareesh88666/maven-web-application
  tag: "1"

service:
  type: ClusterIP
  port: 80

activeVersion: green     # TRAFFIC GOES TO BLUE

ingress:
  enabled: false
  className: "nginx"

