version: green
replicaCount: 2

image:
  repository: hareesh88666/maven-web-application
  tag: "2"

service:
  type: ClusterIP
  port: 80

activeVersion: blue     # TRAFFIC STILL GOES TO BLUE INITIALLY

ingress:
  enabled: true
  className: "nginx"

