version: green
replicaCount: 2

image:
  repository: hareesh88666/maven-web-application
  tag: "2"

service:
  port: 80

activeVersion: green    # traffic to green (only when switching)

ingress:
  enabled: false        # green should not create ingress

serviceEnabled: false
