version: blue
replicaCount: 2
image:
  repository: hareesh88666/maven-web-application
  tag: "5"
service:
  port: 80
activeVersion: green                      # traffic to blue
ingress:
  enabled: true                          # blue owns ingress
fullnameOverride: maven-webapp
serviceEnabled: true
