{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "maven-webapp.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingress.className }}"
spec:
  rules:
    - host: "{{ .Values.ingress.hosts.host }}"
      http:
        paths:
          - path: "{{ .Values.ingress.hosts.path }}"
            pathType: "{{ .Values.ingress.hosts.pathType }}"
            backend:
              service:
                name: {{ include "maven-webapp.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
